name: Flutter CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: app

      - name: Analyze project source
        run: flutter analyze
        working-directory: app

      - name: Run tests
        run: flutter test
        working-directory: app
